name: Browser Tests

on:
  push:
    branches:
      - main
    paths:
      - "src.ts/**"
      - "lib.esm/**"
      - "lib.commonjs/**"
      - "misc/test-browser/**"

jobs:
  test-browser:
    name: Run Browser Tests

    runs-on: ubuntu-latest

    environment: ethers-tests

    strategy:
      fail-fast: false

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install and run Geth
        uses: ethers-io/run-geth-action@main

      - name: Insall Chrome
        run: wget -q 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' && sudo dpkg --install google-chrome-stable_current_amd64.deb

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build browser bundles (from TypeScript)
        run: npm run build-dist
        
      - name: Run tests
        run: npm run test-browser
