name: Environment Tests

on:
  push:
    branches:
      - main

jobs:

  test-tsc-env:
    name: Test TypeScript Environments

    runs-on: ubuntu-latest

    env:
      npm_config_registry: http://localhost:8043

    strategy:
      fail-fast: false
      matrix:
        tsModuleResolution: [ "node", "node16", "nodenext" ]
        tsModule: [ "commonjs", "es2020" ]

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: "faux_modules/ethers"

      - name: Copy tests to working directory
        run: cp -r faux_modules/ethers/testcases/test-env/test-tsc/* .

      - name: Prepare setup moduleResolution=${{ matrix.tsModuleResolution }} module=${{ matrix.tsModule }}
        run: node prepare.cjs ${{ matrix.tsModuleResolution }} ${{ matrix.tsModule }}

      - name: Dump Config
        run: cat package.json tsconfig.json

      - name: Install and run Faux Registry
        uses: ethers-io/hijack-npm-action@main

      - name: Install packages
        run: npm install

      - name: Dump Faux Logs
        run: cat .fauxNpm.log

      - name: Run tests
        run: npm test

  test-angular:
    name: Test Angular Environment

    runs-on: ubuntu-latest

    env:
      npm_config_registry: http://localhost:8043

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: "faux_modules/ethers"

      - name: Copy tests to working directory
        run: cp -r faux_modules/ethers/testcases/test-env/angular/* .

      - name: Install and run Faux Registry
        uses: ethers-io/hijack-npm-action@main

      - name: Install packages
        run: npm install

      - name: Build project
        run: npm run build

